### PR TITLE
Remove path prefix from environments in default location

### PR DESCRIPTION
**Pull request by 3mb3dw0rk5**
For better readability I removed the path prefixes from environments in standard location .conda/venvs

### CODE REVIEW

**Comment by esc** [comment]
Hi and thank you for your submission. Unfortunately, it seems like this PR is now in conflict with master, can you fix?

**Comment by esc** [comment]
@3mb3dw0rk5 ping on this one, pls.

**Comment by 3mb3dw0rk5** [comment]
Sorry for the late update. I somehow missed that topic ;-)

**Comment by esc** [comment]
@3mb3dw0rk5 thank you for the fixes!

**Pull request merged**
