### PR TITLE
fix alignment, bit hacky, but works

### LINKED ISSUE #5: Bad alignment
I am seeing bad alignment in my conda completions when using menu selection. I really have no idea how this works though, so I'm not sure if this is the completion's fault or zsh.

I am using zsh v5.3.1 on macOS 10.13 beta:

```
% zsh --version
zsh 5.3.1 (x86_64-apple-darwin17.0.0)
```

The relevant section of my zshrc:

```
# Completion
#--------------------
autoload -Uz compinit && compinit -u

zstyle ':completion:*' use-cache true # Cache completion to `${ZDOTDIR}/.zcompcache`
zstyle ':completion:*' squeeze-slashes true # Strip slashes from directories
zstyle ':completion:*' menu select # Make the menu interactive with arrow keys

bindkey '^I' menu-expand-or-complete
bindkey '^[[Z' reverse-menu-complete
```

The results I am seeing:

```
% conda build
build  -- tool for building conda packages
bundle   -- Create or extract a "bundle package" (EXPERIMENTAL)
clean   -- Remove unused packages and caches.
config  -- Modify configuration values in .condarc.
create     -- Create a new conda environment from a list of specified packages.
env    -- Manage environments.
help  -- Displays a list of available conda commands and their help strings.
info       -- Display information about current conda install.
init     -- Initialize conda into a regular environment. (DEPRECATED)
install  -- Install a list of packages into a specified conda environment.
list       -- List linked packages in a conda environment.
package  -- Low-level conda package utility. (EXPERIMENTAL)
remove     -- Remove a list of packages from a specified conda environment.
run      -- Launches an application installed with Conda.
search   -- Search for packages and display their information.
uninstall  -- Alias for conda remove
update  -- Update conda packages.
```

_conda

### PR DESCRIPTION
**Pull request by esc**
fixes #5 - potentially.

### CODE REVIEW

**Comment by esc** [comment]
kinda sucks, because the alignment is manual, but oh well.

**Comment by cbarrick** [comment]
This doesn't quite work for me. When I type `conda b<tab>` I get this:

```console
$ conda build\ \ \ \ \
build       -- tool for building conda packages
bundle      -- Create or extract a "bundle package" (EXPERIMENTAL)
```

It seems that zsh is escaping the extra spaces before it performs the completion. Inserting spaces, escaped or not, is worse IMO than bad alignment.

**Comment by esc** [comment]
Bummer, might be time to ask on the zsh mailinglist

**Comment by esc** [comment]
@cbarrick yeah, I get this error too.

**Comment by cgjosephlee** [comment]
I would recommend to refactor `__conda_commands` like #9 to fix #5.

**Comment by esc** [comment]
@cgjosephlee unfortunately that removes the command sections and thus fixes a bug for some people and removes a feature for others.

**Comment by esc** [comment]
New attempt in #13 @cbarrick and @cgjosephlee can you check it out?

**Comment by esc** [comment]
Superseded by #15

**Pull request closed without merging**
