### PR TITLE
Enable loading as zsh custom plugin

### PR DESCRIPTION
**Pull request by vmiheer**

### CODE REVIEW

**Comment by vmiheer** [comment]
I have tested this change locally. I found inspiration about doing this commit at https://github.com/zsh-users/zsh-completions#oh-my-zsh.

**Comment by vmiheer** [comment]
@esc, @apjanke, @taylorkangbeck will you please review this change?

**Comment by esc** [comment]
@vmiheer thanks for your contribution! I don't use OMZ myself, so I am unable to review this change. I will happily merge it however, if I can get confirmation from other OMZ users that this is a good and working solution.

**Comment by levbishop** [comment]
it seems to work in OMZ with this patch

**Comment by esc** [comment]
@levbishop thanks 🙏 I trust your judgement.

**Pull request merged**
